import java.util.Scanner;

public class Main {

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);

//        Task 3: A Visual Update
//        The grand opening day is over and went great! While interacting with potential customers, we got a lot of ideas,
//        for example, about a new logo. Supposedly, you can draw pretty spirals by using the Fibonacci sequence as a guide.
//        The Fibonacci sequence is a sequence of numbers where each new number is generated by adding the two previous numbers.
//        The first few Fibonacci numbers are: 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, .... etc.
//        To create a really beautiful spiral-logo, the designer needs only 40 Fibonacci numbers for reference.
//
//                Create an application that:
//
//        prints 40 Fibonacci numbers
        
        int first = 1;
        int second = 1;
        int third = 0;
        System.out.println(first);
        System.out.println(second);

        for (int i = 0; i < 40; i++) {
            third = first + second;
            System.out.println(third);
            first = second;
            second = third;

        }
    }

}

